# Generated by Django 5.0 on 2023-12-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultentapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultentprofile',
            name='category',
        ),
        migrations.AddField(
            model_name='consultentprofile',
            name='category',
            field=models.ManyToManyField(to='consultentapp.categorymodel'),
        ),
    ]
