# Generated by Django 5.0 on 2023-12-18 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultentapp', '0003_alter_consultentprofile_average_rating_reviewmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultentprofile',
            name='average_rating',
        ),
    ]
