# Generated by Django 5.0 on 2023-12-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultentapp', '0004_remove_consultentprofile_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultentprofile',
            name='average_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
