# Generated by Django 5.0 on 2023-12-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultentapp', '0005_consultentprofile_average_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultentprofile',
            name='average_rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
