# Generated by Django 5.0 on 2024-01-06 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_customuser_is_profile_completed'),
        ('consultentapp', '0007_consultentprofile_instagram_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speakers',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authapp.customuser',),
        ),
        migrations.CreateModel(
            name='Consultents',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authapp.customuser',),
        ),
        migrations.CreateModel(
            name='SpeakersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_name', models.CharField(blank=True, max_length=300, null=True)),
                ('title', models.CharField(blank=True, max_length=400, null=True)),
                ('profile_image', models.ImageField(upload_to='profile-pics')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_meetings', models.IntegerField(blank=True, null=True)),
                ('meetings_cancelled', models.IntegerField(blank=True, null=True)),
                ('average_rate', models.FloatField(blank=True, default=0, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('category', models.ManyToManyField(to='consultentapp.categorymodel')),
                ('languages', models.ManyToManyField(to='consultentapp.languagemodel')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultentapp.locationmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultentapp.speakers')),
            ],
        ),
        migrations.AlterField(
            model_name='consultentprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultentapp.consultents'),
        ),
    ]
