# Generated by Django 5.0 on 2024-01-06 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultentapp', '0008_speakers_consultents_speakersmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speakersmodel',
            old_name='meetings_cancelled',
            new_name='events_cancelled',
        ),
        migrations.RenameField(
            model_name='speakersmodel',
            old_name='total_meetings',
            new_name='total_events',
        ),
    ]
