# Generated by Django 5.0 on 2024-01-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_customuser_is_profile_completed'),
        ('consultentapp', '0009_rename_meetings_cancelled_speakersmodel_events_cancelled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultentprofile',
            name='category',
            field=models.ManyToManyField(to='authapp.interestmodel'),
        ),
    ]
