# Generated by Django 5.0 on 2024-01-25 02:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultentapp", "0010_alter_consultentprofile_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "speaker_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "speaker_tagline",
                    models.CharField(blank=True, max_length=800, null=True),
                ),
                (
                    "achievement_one",
                    models.CharField(blank=True, max_length=800, null=True),
                ),
                (
                    "subachievement_one",
                    models.CharField(blank=True, max_length=800, null=True),
                ),
                (
                    "achievement_two",
                    models.CharField(blank=True, max_length=800, null=True),
                ),
                (
                    "subachievement_two",
                    models.CharField(blank=True, max_length=800, null=True),
                ),
                (
                    "achievement_three",
                    models.CharField(blank=True, max_length=800, null=True),
                ),
                (
                    "subachievement_three",
                    models.CharField(blank=True, max_length=800, null=True),
                ),
                (
                    "achievement_four",
                    models.CharField(blank=True, max_length=800, null=True),
                ),
                (
                    "subachievement_four",
                    models.CharField(blank=True, max_length=800, null=True),
                ),
                ("event_date", models.DateField()),
                ("event_time", models.TimeField()),
            ],
        ),
    ]
