# Generated by Django 5.0 on 2024-01-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultentapp", "0011_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile-pics"),
        ),
    ]
