# Generated by Django 5.0 on 2024-02-02 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultentapp", "0013_event_upcomming"),
    ]

    operations = [
        migrations.CreateModel(
            name="Community_cateogry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cat", models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="insta_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Community",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("community_name", models.CharField(max_length=300)),
                (
                    "community_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="community-pics"
                    ),
                ),
                ("members", models.IntegerField()),
                ("community_desc", models.TextField(blank=True, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "cateogry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="consultentapp.community_cateogry",
                    ),
                ),
            ],
        ),
    ]
