# Generated by Django 5.0.6 on 2024-06-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultentapp', '0014_community_cateogry_event_insta_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='free_left',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_free_session',
            field=models.BooleanField(default=False),
        ),
    ]
