# Generated by Django 5.0 on 2023-12-16 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultbooking',
            old_name='preferred_data',
            new_name='preferred_date',
        ),
    ]
