# Generated by Django 5.0 on 2023-12-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0002_rename_preferred_data_consultbooking_preferred_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultbooking',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
