# Generated by Django 5.0 on 2023-12-25 14:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0003_consultbooking_amount'),
        ('consultentapp', '0006_alter_consultentprofile_average_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultbooking',
            name='preferred_date',
        ),
        migrations.RemoveField(
            model_name='consultbooking',
            name='question',
        ),
        migrations.RemoveField(
            model_name='consultbooking',
            name='required_time',
        ),
        migrations.CreateModel(
            name='TimeSlotModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_booked', models.BooleanField(default=False)),
                ('day', models.DateField()),
                ('time', models.TimeField()),
                ('consultent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultentapp.consultentprofile')),
            ],
        ),
        migrations.AddField(
            model_name='consultbooking',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookingapp.timeslotmodel'),
        ),
    ]
