# Generated by Django 5.0 on 2023-12-25 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0004_remove_consultbooking_preferred_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultbooking',
            name='time_slot',
        ),
        migrations.DeleteModel(
            name='TimeSlotModel',
        ),
    ]
