# Generated by Django 5.0 on 2024-01-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0005_remove_consultbooking_time_slot_delete_timeslotmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultbooking',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
